import type { NextPage } from 'next'
import Head from 'next/head'
import {StyledContainer} from '../styles/muiStyles'
import Navigation from '../components/Navigation';
import Newsletter from '../components/Newsletter';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Banana Belt Liquors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/banana.png" />
      </Head>

    <StyledContainer disableGutters>
      <Navigation/>
      <Newsletter/>
    </StyledContainer>
         

   
    </div>
  )
}

export default Home
